govtrack/govtrack.us-web

- .gitignore
- README.md
- build/buildenv.sh
- build/pipreq.txt
> Changes to make project work on OS X

- parse.py
- vote/models.py
- vote/search.py
- vote/views.py
I figured out how to add the sort. Not sure about the changes to parse.py. I needed to make those to get it running locally. What should I do about those changes?
> Added functionality to sort by yes vote

- templates/ask_district.html
The "and" in this sentence should have the same parts of speech on either side
> "Follow us?" modal dialog: parallel structure

- settings_local.example.py
This is needed to get a development server running
> Add Twilio configuration to example settings file

- templates/master.html
This fixes #56. I tested it locally, and it looks good.
> Keep query string when returning from login/logout

- README.md
This was the only problem I encountered during the new automated setup.  super cool!
> fix error about no TTY

- templates/bill/bill_key_questions.html
With an average of 500 users a day we should hopefully get some responses
> Add google form to study guide pages

- stakeholder/views.py
allow stakeholders to edit posts, deny double posts
> Editstakeholderpost

- stakeholder/views.py
Set link requirement to false. It's too much of a barrier for posting.
> Don't require links

- templates/website/covid19.html
> add brindisi

- templates/website/covid19.html
> david price

- templates/website/covid19.html
> sharice davids

- templates/website/covid19.html
> vicente gonzalez

- templates/website/covid19.html
Left original entry w/Romney alone since his move to close his office preceded Rand Paul & seems to be separate.
> Added Lee & Romney

- templates/website/covid19.html
> fixed typos, updated porter, cunningham;

- templates/website/for-advocates.html
Offer advocates to send us their congressional scorecards
> scorecards

- templates/website/covid19.html
He says he "contracted it" on June 8. I don't know if that means he had symptoms that day or got test results or what. So until I learn differently, I'm assuming he'll stay quarantined for two weeks from yesterday.
> added tom rice

- templates/website/covid19.html
> somehow introduced another typo

- templates/website/about.html
Remove "\" from about.html because it was causing a red bar at the top
> Remove "\"

- templates/website/covid19.html
kaine (antibodies), casey (antibodies), gaetz (antibodies), waltz (regular positive), allen (regular positive), nunes (antibodies), wilson (regular positive)
> bunch of adds

- settings_env.py
- templates/master.html
- templates/site-news-banner.html
- templates/website/voterama.html
- website/urls.py
- website/views.py
Add announcement and sign up page for Voterama
> Voterama announcement

- templates/committee/game.html
Write out both for loops to compare lists
> fix committee game alert

- templates/website/covid19.html
I think Salazar is the only rep/rep-elect still in quarantine.
> added new rep salazar; existing rep brady

- templates/website/covid19.html
he explicitly says he's in isolation for 10 days, so that's what I've followed on dates.
> added armstrong

- templates/website/covid19.html
> added brian babin

- templates/website/covid19.html
as 6/1 bc he says in the clip in the tweet linked in the entry that it was "early in the summer". He also says he "felt sick" and he was "back in Ohio", but not whether he isolated. Thus my entry.
> jordan added

- templates/website/covid19.html
bc he's got cancer rn, he's at Mayo for an indeterminate time. Thus, I gave him a full 14 day expected end date.
> covid19: Hagerdorn, McCaul, Kim, Ocasio-Cortez, Katko, Cline

- templates/website/covid19.html
inhofe, underwood, raskin, delbene, padilla, aguilar, deutch, evans
> added a bunch

- templates/website/covid19.html
schiff, castro, wasserman schultz, clark, peters, kilmer, meeks, pelosi, collins, craig, warnock, defazio, krishnamoorthi
> added 14 this week

- templates/website/covid19.html
covers 4/11-4/21, so I think we're safe to update.
> added tlaib, moore (again), maloney, levin

- templates/website/covid19.html
ruppersberger, murkowski; also fixed a typo
> added smith, miller, connolly, carper, manchin
